version: '3'

services:
  db:
    image: postgres:11
    expose:
      - 5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
  web:
    build: ./code
    command: bash -c "python manage.py migrate && python manage.py collectstatic --no-input  && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    volumes:
      - ./code/banana/static:/opt/banana/static

  nginx-ssl-proxy:
    image: danieldent/nginx-ssl-proxy
    restart: always
    environment:
      UPSTREAM: web:8000
      SERVERNAME: nepha.net
      EXTRANAMES: www.nepha.net
    ports:
      - "80:80"
      - "443:443"
    volumes:
          - ./data/letsencrypt:/etc/letsencrypt
          - ./code/static_root:/opt/monadical/example-django-devops/code/banana/static
          - ./etc/nginx/conf.d/default.conf:/etc/nginx/main_location.conf

volumes:
  pg_data:
